'use client';

import Link from 'next/link';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import MembershipStatusBadge from '../../memberships/MembershipStatusBadge';
import { currencyFormatter, expiryLabel, formatDate } from '../../memberships/format';
import type { MembershipRecord } from '../../memberships/types';

interface ResponseData { currentMembership: MembershipRecord | null; memberships: MembershipRecord[]; total: number; totalPages: number; }

export default function MemberMemberships({ memberId }: { memberId: string }) {
  const router = useRouter(); const [data, setData] = useState<ResponseData | null>(null); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reload, setReload] = useState(0); const [cancel, setCancel] = useState<MembershipRecord | null>(null);
  useEffect(() => { const c = new AbortController(); async function load() { setLoading(true); setError(''); try { const response = await fetch(`/api/members/${encodeURIComponent(memberId)}/memberships?page=${page}&limit=6`, { signal: c.signal }); if (response.status === 401) { router.replace('/login'); return; } if (!response.ok) throw new Error(); setData(await response.json() as ResponseData); } catch (e) { if (!(e instanceof DOMException && e.name === 'AbortError')) setError('Membership information could not be loaded.'); } finally { if (!c.signal.aborted) setLoading(false); } } void load(); return () => c.abort(); }, [memberId, page, reload, router]);
  const refresh = useCallback(() => { setPage(1); setReload((v) => v + 1); }, []);
  if (loading && !data) return <section aria-label="Membership information loading" className="h-64 animate-pulse rounded-xl border border-gray-200 bg-white" />;
  if (error && !data) return <section className="rounded-xl border border-red-200 bg-red-50 p-6 text-center"><h2 className="font-semibold text-red-900">Unable to load memberships</h2><p className="mt-1 text-sm text-red-700">{error}</p><button onClick={refresh} className="mt-4 rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white">Try again</button></section>;
  const current = data?.currentMembership;
  return <div className="space-y-5">
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 className="text-lg font-semibold text-gray-900">Current Membership</h2><p className="mt-1 text-sm text-gray-500">The member&apos;s presently active plan.</p></div>{!current && <Link href={`/dashboard/members/${encodeURIComponent(memberId)}/membership/new`} className="rounded-lg bg-blue-600 px-4 py-2.5 text-center text-sm font-semibold text-white hover:bg-blue-700">Assign Membership</Link>}</div>
      {current ? <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50/60 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xl font-bold text-gray-900">{current.plan.name}</p><p className="mt-1 text-sm font-medium text-emerald-800">{expiryLabel(current.endDate, current.status)}</p></div><MembershipStatusBadge status={current.status} /></div><dl className="mt-5 grid gap-3 sm:grid-cols-3"><Item label="Start date" value={formatDate(current.startDate)} /><Item label="Expiry date" value={formatDate(current.endDate)} /><Item label="Purchase price" value={currencyFormatter.format(current.priceAtPurchase)} /></dl>{current.notes && <div className="mt-3"><Item label="Notes" value={current.notes} /></div>}<div className="mt-5 flex flex-col gap-2 sm:flex-row"><button onClick={() => setCancel(current)} className="rounded-lg border border-red-300 bg-white px-4 py-2.5 text-sm font-semibold text-red-700 hover:bg-red-50">Cancel Membership</button><span className="self-center text-xs text-gray-500">Renewal becomes available after this membership expires or is cancelled.</span></div></div>
      : <div className="mt-5 rounded-xl border border-dashed border-gray-300 bg-gray-50 px-6 py-10 text-center"><h3 className="font-semibold text-gray-900">No active membership</h3><p className="mt-2 text-sm text-gray-500">Assign a plan or renew using a new membership record. Previous records remain in history.</p><Link href={`/dashboard/members/${encodeURIComponent(memberId)}/membership/new`} className="mt-4 inline-block text-sm font-semibold text-blue-700">Assign or Renew Membership →</Link></div>}
    </section>
    <section className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-6"><div><h2 className="text-lg font-semibold text-gray-900">Membership History</h2><p className="mt-1 text-sm text-gray-500">Commercial history is preserved for every assignment.</p></div>{error && <div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}
      {!data?.memberships.length ? <div className="mt-5 rounded-lg bg-gray-50 p-8 text-center text-sm text-gray-500">No membership history yet.</div> : <div className="mt-5 space-y-3">{data.memberships.map((membership) => <article key={membership._id} className="rounded-lg border border-gray-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-gray-900">{membership.plan.name}</h3><p className="mt-1 text-xs text-gray-500">{expiryLabel(membership.endDate, membership.status)}</p></div><MembershipStatusBadge status={membership.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Item label="Start" value={formatDate(membership.startDate)} /><Item label="End" value={formatDate(membership.endDate)} /><Item label="Purchase price" value={currencyFormatter.format(membership.priceAtPurchase)} /><Item label="Assigned" value={formatDate(membership.createdAt)} /></dl>{membership.notes && <p className="mt-3 rounded bg-gray-50 p-3 text-sm text-gray-700"><span className="font-semibold">Notes:</span> {membership.notes}</p>}</article>)}</div>}
      {(data?.totalPages || 0) > 1 && <div className="mt-4 flex items-center justify-end gap-2"><button disabled={page === 1 || loading} onClick={() => setPage((v) => v - 1)} className="rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-40">Previous</button><span className="text-sm text-gray-600">Page {page} of {data?.totalPages}</span><button disabled={page === data?.totalPages || loading} onClick={() => setPage((v) => v + 1)} className="rounded-lg border px-3 py-2 text-sm font-semibold disabled:opacity-40">Next</button></div>}
    </section>{cancel && <CancelMembershipDialog membership={cancel} onClose={() => setCancel(null)} onSuccess={() => { setCancel(null); refresh(); }} />}
  </div>;
}

function Item({ label, value }: { label: string; value: string }) { return <div className="min-w-0"><dt className="text-xs font-semibold uppercase tracking-wide text-gray-500">{label}</dt><dd className="mt-1 break-words text-sm font-semibold text-gray-900">{value}</dd></div>; }

function CancelMembershipDialog({ membership, onClose, onSuccess }: { membership: MembershipRecord; onClose: () => void; onSuccess: () => void }) {
  const router = useRouter(); const cancelRef = useRef<HTMLButtonElement>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { cancelRef.current?.focus(); function key(e: KeyboardEvent) { if (e.key === 'Escape' && !busy) onClose(); } document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [busy, onClose]);
  async function confirm() { setBusy(true); setError(''); try { const response = await fetch(`/api/memberships/${encodeURIComponent(membership._id)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: 'cancelled' }) }); if (response.status === 401) { router.replace('/login'); return; } if (!response.ok) { setError(response.status === 404 ? 'This membership no longer exists.' : response.status === 409 ? 'This membership is no longer active and cannot be cancelled.' : 'The membership could not be cancelled. Please try again.'); return; } onSuccess(); } catch { setError('The membership could not be cancelled. Check your connection and try again.'); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-gray-950/60 p-4" onMouseDown={(e) => { if (e.target === e.currentTarget && !busy) onClose(); }}><div role="dialog" aria-modal="true" aria-labelledby="cancel-title" aria-describedby="cancel-description" className="w-full max-w-md rounded-xl bg-white p-6 shadow-2xl"><h2 id="cancel-title" className="text-lg font-bold text-gray-900">Cancel active membership?</h2><p id="cancel-description" className="mt-2 text-sm leading-6 text-gray-600">This ends the active <strong>{membership.plan.name}</strong> membership. The record will not be deleted and remains visible in history.</p>{error && <div role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mt-6 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button ref={cancelRef} disabled={busy} onClick={onClose} className="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold disabled:opacity-50">Keep Membership</button><button disabled={busy} onClick={confirm} className="rounded-lg bg-red-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Cancelling…' : 'Cancel Membership'}</button></div></div></div>;
}
