'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { MemberRecord } from '../../../types';
import { currencyFormatter, durationLabel, expectedEndDate, formatDate } from '../../../../memberships/format';
import type { MembershipPlanRecord, PlansResponse } from '../../../../memberships/types';

const input = 'mt-1.5 w-full rounded-lg border border-gray-300 bg-white px-3.5 py-2.5 text-sm text-gray-900 outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 disabled:bg-gray-100';
function localToday() { const d = new Date(); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 10); }

export default function MembershipAssignmentPageClient({ memberId }: { memberId: string }) {
  const router = useRouter(); const [member, setMember] = useState<MemberRecord | null>(null); const [plans, setPlans] = useState<MembershipPlanRecord[]>([]); const [planId, setPlanId] = useState(''); const [startDate, setStartDate] = useState(localToday); const [notes, setNotes] = useState(''); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(''); const [formError, setFormError] = useState(''); const [busy, setBusy] = useState(false); const [retry, setRetry] = useState(0);
  const selected = useMemo(() => plans.find((plan) => plan._id === planId), [planId, plans]);
  const backHref = `/dashboard/members/${encodeURIComponent(memberId)}`;
  useEffect(() => { const c = new AbortController(); async function load() { setLoading(true); setLoadError(''); try { const [memberResponse, plansResponse] = await Promise.all([fetch(`/api/members/${encodeURIComponent(memberId)}`, { signal: c.signal }), fetch('/api/membership-plans?status=active&limit=100', { signal: c.signal })]); if (memberResponse.status === 401 || plansResponse.status === 401) { router.replace('/login'); return; } if (memberResponse.status === 404) { setLoadError('This member could not be found.'); return; } if (!memberResponse.ok || !plansResponse.ok) throw new Error(); const memberData = await memberResponse.json() as { member: MemberRecord }; const planData = await plansResponse.json() as PlansResponse; setMember(memberData.member); setPlans(planData.plans); if (planData.plans.length === 1) setPlanId(planData.plans[0]._id); } catch (e) { if (!(e instanceof DOMException && e.name === 'AbortError')) setLoadError('The assignment form could not be loaded. Please try again.'); } finally { if (!c.signal.aborted) setLoading(false); } } void load(); return () => c.abort(); }, [memberId, retry, router]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setFormError(''); if (!planId) { setFormError('Select a membership plan.'); return; } if (!startDate || Number.isNaN(new Date(`${startDate}T00:00:00`).getTime())) { setFormError('Enter a valid start date.'); return; } if (notes.trim().length > 1000) { setFormError('Notes cannot exceed 1000 characters.'); return; } setBusy(true); try { const response = await fetch('/api/memberships', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ memberId: member?.memberId || memberId, planId, startDate, notes: notes.trim() }) }); if (response.status === 401) { router.replace('/login'); return; } const result = await response.json().catch(() => null) as { error?: string; details?: string[] } | null; if (!response.ok) { if (response.status === 409) setFormError(result?.error === 'Member already has an active membership' ? 'This member already has an active membership. Cancel it or wait for expiry before renewing.' : result?.error || 'This membership cannot be assigned.'); else if (response.status === 404) setFormError(result?.error === 'Member not found' ? 'This member no longer exists.' : 'The selected plan is no longer available. Choose another active plan.'); else setFormError(result?.details?.join(' ') || 'The membership could not be assigned. Please try again.'); return; } router.push(`${backHref}?membership=assigned`); router.refresh(); } catch { setFormError('The membership could not be assigned. Check your connection and try again.'); } finally { setBusy(false); } }
  if (loading) return <div role="status" className="mx-auto max-w-3xl animate-pulse space-y-5"><div className="h-8 w-64 rounded bg-gray-200" /><div className="h-96 rounded-xl bg-white" /></div>;
  if (loadError || !member) return <div className="mx-auto max-w-3xl rounded-xl border border-red-200 bg-red-50 p-8 text-center"><h1 className="font-bold text-red-900">Unable to assign membership</h1><p className="mt-2 text-sm text-red-700">{loadError}</p><div className="mt-5 flex justify-center gap-3"><Link href={backHref} className="rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-800">Back</Link><button onClick={() => setRetry((v) => v + 1)} className="rounded-lg bg-red-700 px-4 py-2 text-sm font-semibold text-white">Try again</button></div></div>;
  return <div className="mx-auto w-full max-w-3xl space-y-5"><header><Link href={backHref} className="text-sm font-semibold text-blue-700">← Back to Member</Link><h1 className="mt-3 text-2xl font-bold text-gray-900 sm:text-3xl">Assign Membership</h1><p className="mt-1 text-sm text-gray-500">A renewal creates a new record and never overwrites earlier history.</p></header><form onSubmit={submit} noValidate className="space-y-6 rounded-xl border border-gray-200 bg-white p-5 shadow-sm sm:p-7">
    <section aria-labelledby="member-summary"><h2 id="member-summary" className="text-sm font-semibold uppercase tracking-wide text-gray-500">Member</h2><div className="mt-2 rounded-lg border border-blue-100 bg-blue-50 p-4"><p className="font-bold text-gray-900">{member.firstName} {member.lastName}</p><p className="mt-1 font-mono text-xs font-semibold text-blue-700">{member.memberId}</p><p className="mt-2 text-sm text-gray-600">{member.phone}{member.email ? ` · ${member.email}` : ''}</p></div></section>
    {plans.length === 0 ? <div role="status" className="rounded-lg border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-900">No active membership plans</p><p className="mt-1 text-sm text-amber-800">Create or activate a plan before assigning a membership.</p><Link href="/dashboard/memberships/plans/new" className="mt-3 inline-block text-sm font-semibold text-amber-900 underline">Add a plan</Link></div> : <><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold text-gray-700 sm:col-span-2">Membership Plan <span className="text-red-600">*</span><select name="planId" value={planId} onChange={(e) => { setPlanId(e.target.value); setFormError(''); }} disabled={busy} className={input}><option value="">Select a plan</option>{plans.map((plan) => <option key={plan._id} value={plan._id}>{plan.name} — {currencyFormatter.format(plan.price)}</option>)}</select></label><label className="text-sm font-semibold text-gray-700">Start date <span className="text-red-600">*</span><input name="startDate" type="date" value={startDate} onChange={(e) => { setStartDate(e.target.value); setFormError(''); }} disabled={busy} className={input} /></label><label className="text-sm font-semibold text-gray-700 sm:col-span-2">Notes <span className="font-normal text-gray-400">(optional)</span><textarea name="notes" value={notes} onChange={(e) => setNotes(e.target.value)} maxLength={1000} disabled={busy} className={`${input} min-h-24 resize-y`} /></label></div>{selected && <section aria-live="polite" className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><h2 className="font-semibold text-emerald-950">Assignment summary</h2><dl className="mt-3 grid gap-3 sm:grid-cols-3"><Summary label="Duration" value={durationLabel(selected.durationMonths)} /><Summary label="Plan price" value={currencyFormatter.format(selected.price)} /><Summary label="Expected end date" value={expectedEndDate(startDate, selected.durationMonths) ? formatDate(expectedEndDate(startDate, selected.durationMonths)) : 'Select a date'} /></dl><p className="mt-3 text-xs text-emerald-800">The server calculates and stores the authoritative end date and purchase price.</p></section>}</>}
    {formError && <div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{formError}</div>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Link href={backHref} className="rounded-lg border border-gray-300 px-4 py-2.5 text-center text-sm font-semibold text-gray-700">Cancel</Link><button disabled={busy || plans.length === 0} className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy ? 'Assigning…' : 'Assign Membership'}</button></div></form></div>;
}

function Summary({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase text-emerald-700">{label}</dt><dd className="mt-1 text-sm font-bold text-emerald-950">{value}</dd></div>; }
